"""add_razorpay_integration

Revision ID: 8ace040fcca1
Revises: 
Create Date: 2026-08-26 14:39:45.038820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ace040fcca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('mandate_id', sa.Uuid(), nullable=True),
    sa.Column('payment_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_type', 'entity_id', name='uq_webhook_event_dedupe')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index('ix_webhook_events_mandate_created_at', 'webhook_events', ['mandate_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_mandate_id'), 'webhook_events', ['mandate_id'], unique=False)
    op.add_column('payment_attempts', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('payment_attempts', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payment_attempts_razorpay_order_id'), 'payment_attempts', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payment_attempts_razorpay_payment_id'), 'payment_attempts', ['razorpay_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_razorpay_payment_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_razorpay_order_id'), table_name='payment_attempts')
    op.drop_column('payment_attempts', 'razorpay_payment_id')
    op.drop_column('payment_attempts', 'razorpay_order_id')
    op.drop_index(op.f('ix_webhook_events_mandate_id'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_mandate_created_at', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
